In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler
import math

filepath = "./heathapps.csv"
df = pd.read_csv(filepath)
df.head()

,Unnamed: 0,App_Names,Reviews,Size,Price,Last Updated,Minimum Android Version,install,Content
0,0,Smart Foods Organic Diet Buddy,411,30.000000,0.0,79,3.000000,50000,0
1,1,Google Fit: Health and Activity Tracking,292197,25.270663,0.0,33,4.142857,10000000,0
2,2,Pedometer,469421,3.300000,0.0,33,4.000000,10000000,0
3,3,"Calorie Counter - MyNetDiary, Food Diary Tracker",30925,26.000000,0.0,34,5.000000,1000000,0
4,4,Map My Hike GPS Hiking,14451,69.000000,0.0,32,5.000000,1000000,0

In [39]:
df = df.drop([df.columns[0],df.columns[1]], axis = 1)
columns = df.columns
df.head()

,Reviews,Size,Price,Last Updated,Minimum Android Version,install,Content
0,411,30.000000,0.0,79,3.000000,50000,0
1,292197,25.270663,0.0,33,4.142857,10000000,0
2,469421,3.300000,0.0,33,4.000000,10000000,0
3,30925,26.000000,0.0,34,5.000000,1000000,0
4,14451,69.000000,0.0,32,5.000000,1000000,0

In [45]:
type(df['Size'][10])

numpy.float64

In [46]:
from sklearn import preprocessing
x = df.values
min_max_scaler = preprocessing.MinMaxScaler()
x_scaled = min_max_scaler.fit_transform(x)
df = pd.DataFrame(x_scaled)
df.columns = columns
df.head()

,Reviews,Size,Price,Last Updated,Minimum Android Version,install,Content
0,0.000085,0.030488,0.0,0.643836,0.285714,0.0001,0.0
1,0.060569,0.025499,0.0,0.013699,0.448980,0.0200,0.0
2,0.097306,0.002321,0.0,0.013699,0.428571,0.0200,0.0
3,0.006410,0.026269,0.0,0.027397,0.571429,0.0020,0.0
4,0.002995,0.071632,0.0,0.000000,0.571429,0.0020,0.0

In [47]:
for i in range(len(df)):
    for j in df.columns:
        if df[j][i] == 0:
            df[j][i] = 0
        else:
            df[j][i] = df[j][i] * math.log(df[j][i])
df.head()

,Reviews,Size,Price,Last Updated,Minimum Android Version,install,Content
0,-0.000797,-0.106417,0.0,-0.283488,-0.357932,-0.000921,0.0
1,-0.169834,-0.093559,0.0,-0.058773,-0.359533,-0.078240,0.0
2,-0.226712,-0.014078,0.0,-0.058773,-0.363128,-0.078240,0.0
3,-0.032371,-0.095601,0.0,-0.098557,-0.319780,-0.012429,0.0
4,-0.017405,-0.188837,0.0,0.000000,-0.319780,-0.012429,0.0

In [50]:
entropies = []

for i in df.columns:
    temp = 0
    for j in range(len(df)):
        temp += df[i][j]/ math.log(len(df))
    entropies.append(temp)
entropies

[-2.56259410430986,
 -9.506223945044056,
 -2.243036911196942,
 -16.219125407301757,
 -41.760785995261585,
 -1.2912464613611825,
 -1.5571306110311018]

In [51]:
diver = []
for i in entropies:
    diver.append(1+i)
diver

[-1.5625941043098601,
 -8.506223945044056,
 -1.243036911196942,
 -15.219125407301757,
 -40.760785995261585,
 -0.2912464613611825,
 -0.5571306110311018]

In [53]:
weights = []
for i in diver:
    weights.append(i/sum(diver))
weights

[0.022932063619572944,
 0.1248342535864348,
 0.01824235830048488,
 0.2233503576596725,
 0.5981904930071215,
 0.004274227300927866,
 0.008176246525785741]

In [54]:
wei = {}
for i in range(len(df.columns)):
    wei[df.columns[i]] = weights[i]
wei

{'Reviews': 0.022932063619572944,
 'Size': 0.1248342535864348,
 'Price': 0.01824235830048488,
 'Last Updated': 0.2233503576596725,
 'Minimum Android Version': 0.5981904930071215,
 'install': 0.004274227300927866,
 'Content': 0.008176246525785741}

In [57]:
df = pd.read_csv("./normalised_data.csv")
df = df.drop([df.columns[0],df.columns[1]], axis = 1)
for i in range(len(df)):
    for j in df.columns:
        df[j][i] = df[j][i] * wei[j]
df.head()

,Size,Price,Last Updated,Minimum Android Version,install,Content
0,0.003806,0.0,0.143801,0.170912,4.273373e-07,0.0
1,0.003183,0.0,0.003060,0.268575,8.548446e-05,0.0
2,0.000290,0.0,0.003060,0.256367,8.548446e-05,0.0
3,0.003279,0.0,0.006119,0.341823,8.548369e-06,0.0
4,0.008942,0.0,0.000000,0.341823,8.548369e-06,0.0

In [104]:
 index1 = [ 2.058906, 2.132748, 1.616580, 1.518577, 1.453638, 2.401481, 1.966739, 1.760794, 1.664742, 1.207536, 1.692347, 1.773873, 1.913659, 1.940569]

In [134]:
s = "3.3939818 1.8449757 1.8618967 1.3459100 1.5550264 1.4938802 1.2479014 1.3044398 1.3044398 1.2898738 0.9953363 1.1837977 1.0880690 1.0203782"
index1 = []
for i in s.split(" "):
    index1.append(float(i))
index1

[3.3939818,
 1.8449757,
 1.8618967,
 1.34591,
 1.5550264,
 1.4938802,
 1.2479014,
 1.3044398,
 1.3044398,
 1.2898738,
 0.9953363,
 1.1837977,
 1.088069,
 1.0203782]

In [135]:
len(index1)

14

In [140]:
s = "0.2946392 0.6926242 0.7881712 0.9039303 0.7739776 0.6881954 0.7742177 0.7382785 0.6795498 0.6681330 0.6856002 0.6915897 0.6340211 0.6712094"
index2 = []
for i in s.split(" "):
#     print(i)
    index2.append(float(i))
index2

[0.2946392,
 0.6926242,
 0.7881712,
 0.9039303,
 0.7739776,
 0.6881954,
 0.7742177,
 0.7382785,
 0.6795498,
 0.668133,
 0.6856002,
 0.6915897,
 0.6340211,
 0.6712094]

In [141]:
# index2= [0.9380430, 0.7624969, 0.7419716, 0.6116217, 0.5447964, 0.5081199 ,0.4903677, 0.4820526, 0.4329278, 0.4709067, 0.3876025, 0.3735439, 0.3448536 ,0.3471664]
len(index2)

14

In [142]:
indexs = pd.DataFrame({
    "Clusters": range(2,16),
    "Davies-Bouldin": index2,
    "Dunns": index1
})
indexs

    Clusters  Davies-Bouldin     Dunns
0          2        0.294639  3.393982
1          3        0.692624  1.844976
2          4        0.788171  1.861897
3          5        0.903930  1.345910
4          6        0.773978  1.555026
5          7        0.688195  1.493880
6          8        0.774218  1.247901
7          9        0.738278  1.304440
8         10        0.679550  1.304440
9         11        0.668133  1.289874
10        12        0.685600  0.995336
11        13        0.691590  1.183798
12        14        0.634021  1.088069
13        15        0.671209  1.020378

In [143]:
array = np.array(index1)
temp = array.argsort()
ranks1 = np.empty_like(temp)
ranks1[temp] = np.arange(len(array))

In [144]:
for i in range(len(index2)):
    index2[i]*=-1
index2

[-0.2946392,
 -0.6926242,
 -0.7881712,
 -0.9039303,
 -0.7739776,
 -0.6881954,
 -0.7742177,
 -0.7382785,
 -0.6795498,
 -0.668133,
 -0.6856002,
 -0.6915897,
 -0.6340211,
 -0.6712094]

In [145]:
array = np.array(index2)
temp = array.argsort()
ranks2 = np.empty_like(temp)
ranks2[temp] = np.arange(len(array))

In [146]:
len(ranks2)

14

In [147]:
indexs["DB Ranks"] = ranks2
indexs["Dunn's"] = ranks1
indexs

    Clusters  Davies-Bouldin     Dunns  DB Ranks  Dunn's
0          2        0.294639  3.393982        13      13
1          3        0.692624  1.844976         5      11
2          4        0.788171  1.861897         1      12
3          5        0.903930  1.345910         0       8
4          6        0.773978  1.555026         3      10
5          7        0.688195  1.493880         7       9
6          8        0.774218  1.247901         2       4
7          9        0.738278  1.304440         4       6
8         10        0.679550  1.304440         9       7
9         11        0.668133  1.289874        11       5
10        12        0.685600  0.995336         8       0
11        13        0.691590  1.183798         6       3
12        14        0.634021  1.088069        12       2
13        15        0.671209  1.020378        10       1

In [148]:
ranks = ranks1+ranks2
len(ranks)

14

In [149]:
array = np.array(ranks)
temp = array.argsort()
ranks3 = np.empty_like(temp)
ranks3[temp] = np.arange(len(array))
len(ranks3)

14

In [150]:
indexs["Final Ranks"] = ranks3
indexs

    Clusters  Davies-Bouldin     Dunns  DB Ranks  Dunn's  Final Ranks
0          2        0.294639  3.393982        13      13           13
1          3        0.692624  1.844976         5      11            9
2          4        0.788171  1.861897         1      12            6
3          5        0.903930  1.345910         0       8            1
4          6        0.773978  1.555026         3      10            7
5          7        0.688195  1.493880         7       9           10
6          8        0.774218  1.247901         2       4            0
7          9        0.738278  1.304440         4       6            4
8         10        0.679550  1.304440         9       7           11
9         11        0.668133  1.289874        11       5           12
10        12        0.685600  0.995336         8       0            2
11        13        0.691590  1.183798         6       3            3
12        14        0.634021  1.088069        12       2            8
13        15        0.671209  1.020378        10       1            5

In [151]:
indexs.to_csv("./indexx.csv")

In [ ]:
"  1   1   1   1   1   1   1   2   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   3   1   1   1   1   1   1   1   3   3   3   1   4   1   1   1   3   3   3   1   4   4   1   1   3   3   3   4   4   1   1   1   5   3   3   6   6   6   1   1 "

In [171]:
stri = "  1   1   1   1   1   1   1   2   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   3   1   1   1   1   1   1   1   3   3   3   1   4   1   1   1   3   3   3   1   4   4   1   1   3   3   3   4   4   1   1   1   5   3   3   6   6   6   1   1 "
clu = []
cnt=0
for i in stri.split("   "):
    if i == "5":
        cnt+=1
    clu.append(int(i))
cnt

1

In [154]:
df = pd.read_csv("./final_cluster.csv")
df.head()

,Reviews,Size,Price,Last.Updated,Minimum.Android.Version,install,Content
0,0.001426,0.009985,5.806235e-63,0.068495,0.428571,0.000517,5.795724e-88
1,0.000210,0.007750,2.456505e-81,0.054795,0.429330,0.000245,3.183981e-133
2,0.002539,0.010246,1.025165e-101,0.041164,0.428571,0.001621,1.631849e-163
3,0.001700,0.010241,9.029556e-87,0.027397,0.428571,0.000526,0.000000e+00
4,0.001568,0.012019,9.938187e-173,0.013699,0.428571,0.000546,0.000000e+00

In [155]:
df['Cluster'] = clu
df

,Reviews,Size,Price,Last.Updated,Minimum.Android.Version,install,Content,Cluster
0,0.001426,0.009985,5.806235e-63,6.849534e-02,0.428571,0.000517,5.795724e-88,1
1,0.000210,0.007750,2.456505e-81,5.479453e-02,0.429330,0.000245,3.183981e-133,1
2,0.002539,0.010246,1.025165e-101,4.116411e-02,0.428571,0.001621,1.631849e-163,1
3,0.001700,0.010241,9.029556e-87,2.739726e-02,0.428571,0.000526,0.000000e+00,1
4,0.001568,0.012019,9.938187e-173,1.369863e-02,0.428571,0.000546,0.000000e+00,1
5,0.002186,0.037252,9.989534e-216,8.359898e-03,0.428571,0.001562,0.000000e+00,1
6,0.001413,0.085954,1.167105e-263,1.588977e-02,0.428571,0.000586,0.000000e+00,1
7,0.005360,0.596327,8.185480e-179,1.930464e-01,0.428690,0.001136,0.000000e+00,2
8,0.000866,0.011005,7.040727e-55,8.219178e-02,0.428571,0.001007,1.500605e-77,1
9,0.000367,0.010300,1.510640e-67,1.007232e-01,0.429536,0.000198,1.887865e-128,1
10,0.006649,0.030894,4.537052e-66,7.737331e-02,0.433254,0.002812,2.001175e-168,1
11,0.001463,0.034567,1.016825e-48,3.615751e-02,0.430186,0.000615,7.743966e-194,1
12,0.005918,0.025733,6.703676e-48,1.321941e-02,0.448979,0.002820,0.000000e+00,1
13,0.002324,0.007772,1.756716e-62,9.680419e-08,0.428572,0.000774,0.000000e+00,1
14,0.066506,0.020821,1.599678e-87,2.608168e-02,0.441657,0.018818,0.000000e+00,1
15,0.035138,0.057967,1.980364e-171,1.421351e-02,0.429181,0.054345,0.000000e+00,1
16,0.007465,0.014216,1.531434e-30,6.289913e-02,0.340698,0.001818,4.315489e-90,1
17,0.004943,0.013390,2.342088e-42,1.259305e-01,0.430140,0.001575,4.463899e-141,1
18,0.004781,0.051743,1.032984e-07,1.139710e-01,0.428574,0.001674,2.573985e-149,1
19,0.000748,0.080455,5.255847e-04,8.063282e-02,0.428546,0.000208,3.825372e-226,1
20,0.006148,0.015824,4.725772e-02,2.078708e-02,0.426405,0.002419,0.000000e+00,1
21,0.029521,0.018549,1.405098e-03,1.388627e-02,0.436252,0.013417,0.000000e+00,1
22,0.132600,0.021319,7.343458e-25,1.406496e-02,0.438920,0.026352,0.000000e+00,1
23,0.429475,0.043023,9.491953e-118,1.077385e-02,0.486531,0.386901,0.000000e+00,1
24,0.000739,0.022413,4.324478e-17,1.217275e-01,0.143023,0.000268,1.429815e-41,3
25,0.003118,0.019486,1.148181e-28,1.438432e-01,0.385057,0.001343,2.275851e-73,1
26,0.001651,0.010811,1.779561e-07,1.587795e-01,0.430764,0.001082,3.129917e-104,1
27,0.002903,0.024707,3.160086e-02,1.462340e-01,0.431249,0.001311,2.190167e-90,1
28,0.000914,0.028416,2.383008e-01,5.287775e-02,0.430823,0.000124,0.000000e+00,1
29,0.000916,0.018898,1.407342e-01,4.301236e-02,0.431548,0.000150,0.000000e+00,1
...,...,...,...,...,...,...,...,...
34,0.003245,0.013123,2.533285e-04,2.026486e-01,0.431366,0.001649,1.024940e-34,3
35,0.002828,0.018632,2.504275e-01,1.239158e-01,0.432933,0.000241,7.764078e-81,1
36,0.000698,0.021919,4.444383e-01,5.141708e-02,0.408148,0.000176,0.000000e+00,4
37,0.002887,0.026399,9.688877e-02,5.875892e-02,0.531651,0.001044,0.000000e+00,1
38,0.002226,0.027959,2.611255e-29,4.136034e-02,0.571429,0.000486,0.000000e+00,1
39,0.005538,0.066561,3.139352e-110,1.190003e-02,0.571429,0.002086,0.000000e+00,1
40,0.000429,0.006231,2.633346e-05,3.823902e-01,0.121285,0.000466,5.001803e-10,3
41,0.000745,0.023730,3.870247e-04,4.027195e-01,0.310056,0.000537,1.354547e-22,3
42,0.000737,0.015311,5.633958e-07,3.419263e-01,0.437241,0.000355,2.440947e-23,3
43,0.000539,0.046903,1.447769e-01,1.687846e-01,0.429878,0.000129,1.527123e-13,1
44,0.003452,0.024032,7.430361e-01,7.954609e-02,0.443397,0.000164,9.006093e-16,4
45,0.001170,0.029516,2.984385e-01,2.538928e-02,0.597397,0.000095,1.663159e-16,4
46,0.000462,0.021780,4.800833e-06,1.123077e-01,0.571429,0.000153,2.220235e-44,1
47,0.001730,0.014207,3.145052e-73,1.388637e-02,0.571429,0.000973,0.000000e+00,1
48,0.000391,0.043307,4.845357e-03,6.352157e-01,0.210310,0.000129,1.527510e-17,3
49,0.007585,0.012040,1.694808e-05,4.919215e-01,0.428528,0.001999,8.822111e-06,3
50,0.002839,0.049906,5.540390e-03,3.181790e-01,0.431231,0.000973,1.762149e-01,3
51,0.005570,0.024243,3.844049e-01,8.069780e-02,0.428177,0.000780,3.315931e-01,4
52,0.010411,0.027108,2.657740e-01,4.689631e-02,0.466383,0.002256,1.913577e-01,4
53,0.007673,0.023596,2.442371e-02,5.407022e-02,0.526371,0.002055,1.609425e-01,1
54,0.001576,0.022382,1.885391e-50,5.238808e-02,0.633415,0.000517,6.538211e-03,1
55,0.000931,0.025691,0.000000e+00,3.733845e-02,0.656823,0.000406,0.000000e+00,1
56,0.001628,0.054714,2.306994e-01,8.714957e-01,0.140019,0.000319,4.515798e-10,5
57,0.000970,0.029165,1.768722e-01,5.574365e-01,0.421525,0.000389,9.806048e-04,3
58,0.002451,0.046619,7.114757e-03,4.741369e-01,0.422043,0.000764,2.844346e-01,3
59,0.004801,0.018709,1.211095e-14,1.038039e-01,0.397615,0.001599,8.006158e-01,6
60,0.010751,0.025733,5.122502e-11,4.182676e-02,0.444027,0.003137,4.712940e-01,6
61,0.012685,0.029542,3.580439e-21,2.914814e-02,0.456487,0.004124,3.333333e-01,6
62,0.005279,0.035143,9.876672e-40,2.085966e-02,0.647207,0.002104,2.385033e-01,1
63,0.001235,0.039845,5.200152e-58,4.513163e-02,0.747936,0.000374,1.134338e-06,1

In [157]:
df1 = df.loc[df['Cluster'] == 1]
df2 = df.loc[df['Cluster'] == 2]
df3 = df.loc[df['Cluster'] == 3]
df4 = df.loc[df['Cluster'] == 4]
df5 = df.loc[df['Cluster'] == 5]
df6 = df.loc[df['Cluster'] == 6]


df1.drop([df.columns[-1]], axis=1)
df2.drop([df.columns[-1]], axis=1)
df3.drop([df.columns[-1]], axis=1)
df4.drop([df.columns[-1]], axis=1)
df5.drop([df.columns[-1]], axis=1)
df6.drop([df.columns[-1]], axis=1)


df1.columns

Index(['Reviews', 'Size', 'Price', 'Last.Updated', 'Minimum.Android.Version',
       'install', 'Content', 'Cluster'],
      dtype='object')

In [158]:
lis = {}
for i in df1.columns:
    temp = []
    temp.append(sum(df1[i])/len(df1))
    temp.append(sum(df2[i])/len(df2))
    temp.append(sum(df3[i])/len(df3))
    temp.append(sum(df4[i])/len(df4))
    temp.append(sum(df5[i])/len(df5))
    temp.append(sum(df6[i])/len(df6))
    lis[i] = temp
lis

{'Reviews': [0.021048411959261576,
  0.00536032940931265,
  0.0021585395616918455,
  0.004260125811732551,
  0.0016284748858656699,
  0.009412250426986233],
 'Size': [0.02831260737273615,
  0.596326983162969,
  0.024327664592885958,
  0.025363706318188118,
  0.0547138457230061,
  0.024661367414035535],
 'Price': [0.02391999541445155,
  8.185479784349205e-179,
  0.016254737889768296,
  0.4272183733447136,
  0.23069937838598,
  1.7079044777642344e-11],
 'Last.Updated': [0.05598742857784426,
  0.19304640614282298,
  0.3683188758867335,
  0.05678931401422144,
  0.8714956993139659,
  0.058259589543807534],
 'Minimum.Android.Version': [0.4744752060781194,
  0.428690376338887,
  0.33813159253592406,
  0.468700248043559,
  0.140018512174111,
  0.4327096412587957],
 'install': [0.01353700151441402,
  0.00113563280647481,
  0.0008239809760549398,
  0.0006941946828516479,
  0.000318877272609058,
  0.0029529655827531865],
 'Content': [0.009666313464678642,
  0.0,
  0.03846990638049511,
  0.1045901685657474,
  4.5157975775389597e-10,
  0.5350810765707873],
 'Cluster': [1.0, 2.0, 3.0, 4.0, 5.0, 6.0]}

In [159]:
cluster_reps = pd.DataFrame(lis)

In [160]:
cluster_reps

,Reviews,Size,Price,Last.Updated,Minimum.Android.Version,install,Content,Cluster
0,0.021048,0.028313,2.392000e-02,0.055987,0.474475,0.013537,9.666313e-03,1.0
1,0.005360,0.596327,8.185480e-179,0.193046,0.428690,0.001136,0.000000e+00,2.0
2,0.002159,0.024328,1.625474e-02,0.368319,0.338132,0.000824,3.846991e-02,3.0
3,0.004260,0.025364,4.272184e-01,0.056789,0.468700,0.000694,1.045902e-01,4.0
4,0.001628,0.054714,2.306994e-01,0.871496,0.140019,0.000319,4.515798e-10,5.0
5,0.009412,0.024661,1.707904e-11,0.058260,0.432710,0.002953,5.350811e-01,6.0

In [161]:
cluster_reps.to_csv("./6Clusters.csv")

In [163]:
df2 = pd.read_csv("./som_cluster.csv")
df2 = df2.drop([df2.columns[0]],axis=1)
df2.head()

    x
0  49
1  15
2  15
3  39
4  40

In [174]:
k = df2.values

In [181]:
t= []
for i in k:
    t.append(i[0])
len(t)

801

In [182]:
df = pd.read_csv("./heathapps.csv")
len(df)

801

In [186]:
df["som_clut"] = t
df = df.drop([df.columns[0]],axis=1)

In [187]:
df.head()

,App_Names,Reviews,Size,Price,Last Updated,Minimum Android Version,install,Content,som_clut
0,Smart Foods Organic Diet Buddy,411,30.000000,0.0,79,3.000000,50000,0,49
1,Google Fit: Health and Activity Tracking,292197,25.270663,0.0,33,4.142857,10000000,0,15
2,Pedometer,469421,3.300000,0.0,33,4.000000,10000000,0,15
3,"Calorie Counter - MyNetDiary, Food Diary Tracker",30925,26.000000,0.0,34,5.000000,1000000,0,39
4,Map My Hike GPS Hiking,14451,69.000000,0.0,32,5.000000,1000000,0,40

In [188]:
td = []
for i in t:
    td.append(clu[i-1])
len(td)

801

In [190]:
cnt = 0
for i in td:
    if i==5:
        cnt+=1
cnt

7

In [192]:
df["Final_clust"] = td
df.head()

,App_Names,Reviews,Size,Price,Last Updated,Minimum Android Version,install,Content,som_clut,Final_clust
0,Smart Foods Organic Diet Buddy,411,30.000000,0.0,79,3.000000,50000,0,49,3
1,Google Fit: Health and Activity Tracking,292197,25.270663,0.0,33,4.142857,10000000,0,15,1
2,Pedometer,469421,3.300000,0.0,33,4.000000,10000000,0,15,1
3,"Calorie Counter - MyNetDiary, Food Diary Tracker",30925,26.000000,0.0,34,5.000000,1000000,0,39,1
4,Map My Hike GPS Hiking,14451,69.000000,0.0,32,5.000000,1000000,0,40,1

In [197]:
df.loc[df["Final_clust"]== 5]

,App_Names,Reviews,Size,Price,Last Updated,Minimum Android Version,install,Content,som_clut,Final_clust
123,Runtastic Workout Timer App,50061,9.2,0.00,105,2.0,1000000,0,57,5
270,Universal Breathing: Pranayama,231,17.0,4.99,85,2.0,5000,0,57,5
272,Health Through Breath,38,27.0,4.99,96,3.0,1000,0,57,5
275,Formula Of Beauty,31,194.0,0.00,98,1.0,5000,0,57,5
479,RunDouble Couch to 5K PRO,214,34.0,1.59,96,2.0,10000,0,57,5
480,Half Marathon PRO by RunDouble,11,34.0,1.59,96,2.0,1000,0,57,5
481,10K PRO by RunDouble,23,34.0,1.59,96,2.0,1000,0,57,5

In [198]:
df.head()

,App_Names,Reviews,Size,Price,Last Updated,Minimum Android Version,install,Content,som_clut,Final_clust
0,Smart Foods Organic Diet Buddy,411,30.000000,0.0,79,3.000000,50000,0,49,3
1,Google Fit: Health and Activity Tracking,292197,25.270663,0.0,33,4.142857,10000000,0,15,1
2,Pedometer,469421,3.300000,0.0,33,4.000000,10000000,0,15,1
3,"Calorie Counter - MyNetDiary, Food Diary Tracker",30925,26.000000,0.0,34,5.000000,1000000,0,39,1
4,Map My Hike GPS Hiking,14451,69.000000,0.0,32,5.000000,1000000,0,40,1

In [2]:
df = pd.read_csv("./Clustered_data.csv")

In [5]:
best_app = df.loc[df["Final_clust"]== 3]
# best_app.to_csv("./best_apps.csv")

In [6]:
len(best_app)

78

In [7]:
best_app

,Unnamed: 0,App_Names,Reviews,Size,Price,Last Updated,Minimum Android Version,install,Content,som_clut,Final_clust
0,0,Smart Foods Organic Diet Buddy,411,30.000000,0.00,79,3.000000,50000,0,49,3
23,23,Plant Nanny - Water Reminder,254816,42.000000,0.00,69,4.000000,1000000,0,50,3
31,31,Progression Workout Tracker,3249,6.300000,0.00,56,4.000000,100000,0,43,3
33,33,FitNotes - Gym Workout Log,18749,2.900000,0.00,46,4.000000,1000000,0,35,3
47,47,Pocket Yoga,2218,25.270663,2.99,72,4.142857,100000,0,58,3
58,58,Self Healing,14645,9.900000,0.00,53,4.000000,500000,0,34,3
61,61,My Chakra Meditation,7730,45.000000,0.00,44,2.000000,500000,0,25,3
65,65,Weight Loss Tracker - RecStyle,21675,5.700000,0.00,49,4.000000,1000000,0,34,3
69,69,Relaxing Sounds,4748,40.000000,0.00,57,4.000000,100000,0,43,3
102,102,My Chakra Meditation 2,1302,31.000000,0.00,44,2.000000,100000,0,25,3
132,132,Rain Sounds - Sleep Ambiance,9110,8.300000,0.00,67,4.000000,100000,0,50,3
148,148,Human Body System,463,7.100000,0.00,61,2.000000,50000,0,41,3
161,161,Pachamanga,876,2.600000,0.00,57,4.000000,50000,0,43,3
166,166,What's Up? - Mental Health App,2978,9.800000,0.00,64,2.000000,100000,0,41,3
169,169,Happy Pregnancy Ticker,8376,6.900000,0.00,57,2.000000,1000000,0,41,3
197,197,Casual dieting-weight manager-,21247,15.000000,0.00,76,4.000000,1000000,0,50,3
211,211,Darker (Screen Filter),15642,25.270663,0.00,46,4.142857,1000000,0,35,3
223,223,Binaural Beats,254,2.300000,0.00,39,2.000000,10000,0,25,3
251,251,Fit! - Fitness Tracker,155,2.300000,0.00,55,4.000000,10000,0,43,3
252,252,??????????????????????,14888,34.000000,0.00,58,4.000000,500000,0,43,3
259,259,Orangetheory OTbeat,572,20.000000,0.00,70,4.000000,100000,0,50,3
269,269,Relax Lite: Stress Relief,3246,28.000000,0.00,65,3.000000,500000,0,42,3
271,271,Universal - Meditation,47,29.000000,0.00,89,2.000000,5000,0,49,3
292,292,ASUS ZenFit,6139,25.270663,0.00,51,4.142857,1000000,0,34,3
295,295,Yoga tools from Sadhguru,4545,44.000000,0.00,78,3.000000,100000,0,49,3
310,310,Noom Walk Pedometer,154739,12.000000,0.00,66,4.000000,10000000,0,50,3
311,311,Noom Monitor,7,63.000000,0.00,57,4.000000,1000,0,43,3
320,320,ageLOC Me,23,41.000000,0.00,50,4.000000,5000,0,34,3
321,321,Relaxing Spa Music,189,16.000000,0.00,33,2.000000,10000,0,25,3
355,355,Farmï¿½cias de Serviï¿½o .net,4709,25.270663,0.00,51,4.142857,500000,0,34,3
...,...,...,...,...,...,...,...,...,...,...,...
538,538,Nourish Perfect Portions,9,4.600000,0.00,50,4.000000,1000,0,34,3
542,542,Round the Bays,15,33.000000,0.00,46,2.000000,1000,0,25,3
566,566,Dona Sangre Andalucï¿½a,200,4.000000,0.00,55,4.000000,10000,0,43,3
606,606,First Aid For Cyclists,167,2.000000,0.00,65,2.000000,10000,0,41,3
614,614,"Omvana: Meditation, Yoga Sleep",4503,34.000000,0.00,74,4.000000,100000,1,59,3
618,618,Heart Rate Monitor,28667,4.600000,0.00,49,3.000000,1000000,0,33,3
619,619,Heart Rate Monitor,23668,2.300000,0.00,55,4.000000,1000000,0,43,3
629,629,????? ??????? ????? ????????,79,4.300000,0.00,47,2.000000,10000,0,25,3
641,641,21 Day Fixï¿½ Tracker ï¿½ Official,460,11.000000,0.00,57,2.000000,100000,0,41,3
681,681,Health Tips 1000,78,3.800000,0.00,38,2.000000,10000,0,25,3
682,682,12 Daily Workout,2,3.500000,0.00,60,3.000000,100,0,42,3
684,684,Select PT for Patients,1,26.000000,0.00,47,4.000000,100,0,35,3
685,685,NovaCare for Patients,2,26.000000,0.00,47,4.000000,100,0,35,3
690,690,??????? ????????,44,4.700000,0.00,56,2.000000,5000,0,41,3
699,699,?????? ?i?,222,27.000000,0.00,77,2.000000,10000,0,49,3
700,700,Dr. Greger's Daily Dozen,4668,15.000000,0.00,47,4.000000,100000,0,35,3
717,717,Wodify,1704,1.600000,0.00,61,4.000000,100000,0,43,3
719,719,Yoga Mudras for 300+ Diseases,19,6.000000,0.00,47,4.000000,1000,0,35,3
720,720,Yoga Poses for 300+ Diseases,134,3.600000,0.00,47,4.000000,100000,0,35,3
722,722,Finger Holding Therapy,5,3.100000,0.00,47,4.000000,1000,0,35,3
723,723,Diabetes Nature Cure,3,6.000000,0.00,47,4.000000,100,0,35,3
724,724,Top 5 Home Remedies for 300+ Diseases,3,7.400000,0.00,47,4.000000,100,0,35,3
749,749,Interval Trainer PRO,384,3.700000,0.00,61,4.000000,10000,0,43,3
752,752,Pedometer,542,1.700000,0.00,57,2.000000,50000,0,41,3
765,765,Ochre Health,7,10.000000,0.00,67,4.000000,500,0,50,3
766,766,Jupiter Health,10,10.000000,0.00,78,4.000000,1000,0,50,3
775,775,Squats,6,4.300000,0.00,56,5.000000,1000,0,43,3
776,776,HandCare Free Cuida tus manos,3,16.000000,0.00,73,2.000000,500,0,49,3
777,777,Lower Blood Pressure,4,165.000000,0.00,90,2.000000,1000,0,49,3
783,783,Women Workout: Home Gym & Cardio,37349,78.000000,0.00,40,2.000000,1000000,0,25,3