In [38]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler
import math

filepath = "./heathapps.csv"
df = pd.read_csv(filepath)
df.head()

,Unnamed: 0,App_Names,Reviews,Size,Price,Last Updated,Minimum Android Version,install,Content
0,0,Smart Foods Organic Diet Buddy,411,30.000000,0.0,79,3.000000,50000,0
1,1,Google Fit: Health and Activity Tracking,292197,25.270663,0.0,33,4.142857,10000000,0
2,2,Pedometer,469421,3.300000,0.0,33,4.000000,10000000,0
3,3,"Calorie Counter - MyNetDiary, Food Diary Tracker",30925,26.000000,0.0,34,5.000000,1000000,0
4,4,Map My Hike GPS Hiking,14451,69.000000,0.0,32,5.000000,1000000,0

In [39]:
df = df.drop([df.columns[0],df.columns[1]], axis = 1)
columns = df.columns
df.head()

,Reviews,Size,Price,Last Updated,Minimum Android Version,install,Content
0,411,30.000000,0.0,79,3.000000,50000,0
1,292197,25.270663,0.0,33,4.142857,10000000,0
2,469421,3.300000,0.0,33,4.000000,10000000,0
3,30925,26.000000,0.0,34,5.000000,1000000,0
4,14451,69.000000,0.0,32,5.000000,1000000,0

In [45]:
type(df['Size'][10])

numpy.float64

In [46]:
from sklearn import preprocessing
x = df.values
min_max_scaler = preprocessing.MinMaxScaler()
x_scaled = min_max_scaler.fit_transform(x)
df = pd.DataFrame(x_scaled)
df.columns = columns
df.head()

,Reviews,Size,Price,Last Updated,Minimum Android Version,install,Content
0,0.000085,0.030488,0.0,0.643836,0.285714,0.0001,0.0
1,0.060569,0.025499,0.0,0.013699,0.448980,0.0200,0.0
2,0.097306,0.002321,0.0,0.013699,0.428571,0.0200,0.0
3,0.006410,0.026269,0.0,0.027397,0.571429,0.0020,0.0
4,0.002995,0.071632,0.0,0.000000,0.571429,0.0020,0.0

In [47]:
for i in range(len(df)):
    for j in df.columns:
        if df[j][i] == 0:
            df[j][i] = 0
        else:
            df[j][i] = df[j][i] * math.log(df[j][i])
df.head()

,Reviews,Size,Price,Last Updated,Minimum Android Version,install,Content
0,-0.000797,-0.106417,0.0,-0.283488,-0.357932,-0.000921,0.0
1,-0.169834,-0.093559,0.0,-0.058773,-0.359533,-0.078240,0.0
2,-0.226712,-0.014078,0.0,-0.058773,-0.363128,-0.078240,0.0
3,-0.032371,-0.095601,0.0,-0.098557,-0.319780,-0.012429,0.0
4,-0.017405,-0.188837,0.0,0.000000,-0.319780,-0.012429,0.0

In [50]:
entropies = []

for i in df.columns:
    temp = 0
    for j in range(len(df)):
        temp += df[i][j]/ math.log(len(df))
    entropies.append(temp)
entropies

[-2.56259410430986,
 -9.506223945044056,
 -2.243036911196942,
 -16.219125407301757,
 -41.760785995261585,
 -1.2912464613611825,
 -1.5571306110311018]

In [51]:
diver = []
for i in entropies:
    diver.append(1+i)
diver

[-1.5625941043098601,
 -8.506223945044056,
 -1.243036911196942,
 -15.219125407301757,
 -40.760785995261585,
 -0.2912464613611825,
 -0.5571306110311018]

In [53]:
weights = []
for i in diver:
    weights.append(i/sum(diver))
weights

[0.022932063619572944,
 0.1248342535864348,
 0.01824235830048488,
 0.2233503576596725,
 0.5981904930071215,
 0.004274227300927866,
 0.008176246525785741]

In [54]:
wei = {}
for i in range(len(df.columns)):
    wei[df.columns[i]] = weights[i]
wei

{'Reviews': 0.022932063619572944,
 'Size': 0.1248342535864348,
 'Price': 0.01824235830048488,
 'Last Updated': 0.2233503576596725,
 'Minimum Android Version': 0.5981904930071215,
 'install': 0.004274227300927866,
 'Content': 0.008176246525785741}

In [57]:
df = pd.read_csv("./normalised_data.csv")
df = df.drop([df.columns[0],df.columns[1]], axis = 1)
for i in range(len(df)):
    for j in df.columns:
        df[j][i] = df[j][i] * wei[j]
df.head()

,Size,Price,Last Updated,Minimum Android Version,install,Content
0,0.003806,0.0,0.143801,0.170912,4.273373e-07,0.0
1,0.003183,0.0,0.003060,0.268575,8.548446e-05,0.0
2,0.000290,0.0,0.003060,0.256367,8.548446e-05,0.0
3,0.003279,0.0,0.006119,0.341823,8.548369e-06,0.0
4,0.008942,0.0,0.000000,0.341823,8.548369e-06,0.0

In [104]:
 index1 = [ 2.058906, 2.132748, 1.616580, 1.518577, 1.453638, 2.401481, 1.966739, 1.760794, 1.664742, 1.207536, 1.692347, 1.773873, 1.913659, 1.940569]

In [134]:
s = "3.3939818 1.8449757 1.8618967 1.3459100 1.5550264 1.4938802 1.2479014 1.3044398 1.3044398 1.2898738 0.9953363 1.1837977 1.0880690 1.0203782"
index1 = []
for i in s.split(" "):
    index1.append(float(i))
index1

[3.3939818,
 1.8449757,
 1.8618967,
 1.34591,
 1.5550264,
 1.4938802,
 1.2479014,
 1.3044398,
 1.3044398,
 1.2898738,
 0.9953363,
 1.1837977,
 1.088069,
 1.0203782]

In [135]:
len(index1)

14

In [140]:
s = "0.2946392 0.6926242 0.7881712 0.9039303 0.7739776 0.6881954 0.7742177 0.7382785 0.6795498 0.6681330 0.6856002 0.6915897 0.6340211 0.6712094"
index2 = []
for i in s.split(" "):
#     print(i)
    index2.append(float(i))
index2

[0.2946392,
 0.6926242,
 0.7881712,
 0.9039303,
 0.7739776,
 0.6881954,
 0.7742177,
 0.7382785,
 0.6795498,
 0.668133,
 0.6856002,
 0.6915897,
 0.6340211,
 0.6712094]

In [141]:
# index2= [0.9380430, 0.7624969, 0.7419716, 0.6116217, 0.5447964, 0.5081199 ,0.4903677, 0.4820526, 0.4329278, 0.4709067, 0.3876025, 0.3735439, 0.3448536 ,0.3471664]
len(index2)

14

In [142]:
indexs = pd.DataFrame({
    "Clusters": range(2,16),
    "Davies-Bouldin": index2,
    "Dunns": index1
})
indexs

    Clusters  Davies-Bouldin     Dunns
0          2        0.294639  3.393982
1          3        0.692624  1.844976
2          4        0.788171  1.861897
3          5        0.903930  1.345910
4          6        0.773978  1.555026
5          7        0.688195  1.493880
6          8        0.774218  1.247901
7          9        0.738278  1.304440
8         10        0.679550  1.304440
9         11        0.668133  1.289874
10        12        0.685600  0.995336
11        13        0.691590  1.183798
12        14        0.634021  1.088069
13        15        0.671209  1.020378

In [143]:
array = np.array(index1)
temp = array.argsort()
ranks1 = np.empty_like(temp)
ranks1[temp] = np.arange(len(array))

In [144]:
for i in range(len(index2)):
    index2[i]*=-1
index2

[-0.2946392,
 -0.6926242,
 -0.7881712,
 -0.9039303,
 -0.7739776,
 -0.6881954,
 -0.7742177,
 -0.7382785,
 -0.6795498,
 -0.668133,
 -0.6856002,
 -0.6915897,
 -0.6340211,
 -0.6712094]

In [145]:
array = np.array(index2)
temp = array.argsort()
ranks2 = np.empty_like(temp)
ranks2[temp] = np.arange(len(array))

In [146]:
len(ranks2)

14

In [147]:
indexs["DB Ranks"] = ranks2
indexs["Dunn's"] = ranks1
indexs

    Clusters  Davies-Bouldin     Dunns  DB Ranks  Dunn's
0          2        0.294639  3.393982        13      13
1          3        0.692624  1.844976         5      11
2          4        0.788171  1.861897         1      12
3          5        0.903930  1.345910         0       8
4          6        0.773978  1.555026         3      10
5          7        0.688195  1.493880         7       9
6          8        0.774218  1.247901         2       4
7          9        0.738278  1.304440         4       6
8         10        0.679550  1.304440         9       7
9         11        0.668133  1.289874        11       5
10        12        0.685600  0.995336         8       0
11        13        0.691590  1.183798         6       3
12        14        0.634021  1.088069        12       2
13        15        0.671209  1.020378        10       1

In [148]:
ranks = ranks1+ranks2
len(ranks)

14

In [149]:
array = np.array(ranks)
temp = array.argsort()
ranks3 = np.empty_like(temp)
ranks3[temp] = np.arange(len(array))
len(ranks3)

14

In [150]:
indexs["Final Ranks"] = ranks3
indexs

    Clusters  Davies-Bouldin     Dunns  DB Ranks  Dunn's  Final Ranks
0          2        0.294639  3.393982        13      13           13
1          3        0.692624  1.844976         5      11            9
2          4        0.788171  1.861897         1      12            6
3          5        0.903930  1.345910         0       8            1
4          6        0.773978  1.555026         3      10            7
5          7        0.688195  1.493880         7       9           10
6          8        0.774218  1.247901         2       4            0
7          9        0.738278  1.304440         4       6            4
8         10        0.679550  1.304440         9       7           11
9         11        0.668133  1.289874        11       5           12
10        12        0.685600  0.995336         8       0            2
11        13        0.691590  1.183798         6       3            3
12        14        0.634021  1.088069        12       2            8
13        15        0.671209  1.020378        10       1            5

In [151]:
indexs.to_csv("./indexx.csv")

In [ ]:
"  1   1   1   1   1   1   1   2   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   3   1   1   1   1   1   1   1   3   3   3   1   4   1   1   1   3   3   3   1   4   4   1   1   3   3   3   4   4   1   1   1   5   3   3   6   6   6   1   1 "

In [153]:
stri = "  1   1   1   1   1   1   1   2   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   3   1   1   1   1   1   1   1   3   3   3   1   4   1   1   1   3   3   3   1   4   4   1   1   3   3   3   4   4   1   1   1   5   3   3   6   6   6   1   1 "
clu = []
for i in stri.split("   "):
    clu.append(int(i))
clu

[1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 3,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 3,
 3,
 3,
 1,
 4,
 1,
 1,
 1,
 3,
 3,
 3,
 1,
 4,
 4,
 1,
 1,
 3,
 3,
 3,
 4,
 4,
 1,
 1,
 1,
 5,
 3,
 3,
 6,
 6,
 6,
 1,
 1]

In [154]:
df = pd.read_csv("./final_cluster.csv")
df.head()

,Reviews,Size,Price,Last.Updated,Minimum.Android.Version,install,Content
0,0.001426,0.009985,5.806235e-63,0.068495,0.428571,0.000517,5.795724e-88
1,0.000210,0.007750,2.456505e-81,0.054795,0.429330,0.000245,3.183981e-133
2,0.002539,0.010246,1.025165e-101,0.041164,0.428571,0.001621,1.631849e-163
3,0.001700,0.010241,9.029556e-87,0.027397,0.428571,0.000526,0.000000e+00
4,0.001568,0.012019,9.938187e-173,0.013699,0.428571,0.000546,0.000000e+00

In [155]:
df['Cluster'] = clu
df

,Reviews,Size,Price,Last.Updated,Minimum.Android.Version,install,Content,Cluster
0,0.001426,0.009985,5.806235e-63,6.849534e-02,0.428571,0.000517,5.795724e-88,1
1,0.000210,0.007750,2.456505e-81,5.479453e-02,0.429330,0.000245,3.183981e-133,1
2,0.002539,0.010246,1.025165e-101,4.116411e-02,0.428571,0.001621,1.631849e-163,1
3,0.001700,0.010241,9.029556e-87,2.739726e-02,0.428571,0.000526,0.000000e+00,1
4,0.001568,0.012019,9.938187e-173,1.369863e-02,0.428571,0.000546,0.000000e+00,1
5,0.002186,0.037252,9.989534e-216,8.359898e-03,0.428571,0.001562,0.000000e+00,1
6,0.001413,0.085954,1.167105e-263,1.588977e-02,0.428571,0.000586,0.000000e+00,1
7,0.005360,0.596327,8.185480e-179,1.930464e-01,0.428690,0.001136,0.000000e+00,2
8,0.000866,0.011005,7.040727e-55,8.219178e-02,0.428571,0.001007,1.500605e-77,1
9,0.000367,0.010300,1.510640e-67,1.007232e-01,0.429536,0.000198,1.887865e-128,1
10,0.006649,0.030894,4.537052e-66,7.737331e-02,0.433254,0.002812,2.001175e-168,1
11,0.001463,0.034567,1.016825e-48,3.615751e-02,0.430186,0.000615,7.743966e-194,1
12,0.005918,0.025733,6.703676e-48,1.321941e-02,0.448979,0.002820,0.000000e+00,1
13,0.002324,0.007772,1.756716e-62,9.680419e-08,0.428572,0.000774,0.000000e+00,1
14,0.066506,0.020821,1.599678e-87,2.608168e-02,0.441657,0.018818,0.000000e+00,1
15,0.035138,0.057967,1.980364e-171,1.421351e-02,0.429181,0.054345,0.000000e+00,1
16,0.007465,0.014216,1.531434e-30,6.289913e-02,0.340698,0.001818,4.315489e-90,1
17,0.004943,0.013390,2.342088e-42,1.259305e-01,0.430140,0.001575,4.463899e-141,1
18,0.004781,0.051743,1.032984e-07,1.139710e-01,0.428574,0.001674,2.573985e-149,1
19,0.000748,0.080455,5.255847e-04,8.063282e-02,0.428546,0.000208,3.825372e-226,1
20,0.006148,0.015824,4.725772e-02,2.078708e-02,0.426405,0.002419,0.000000e+00,1
21,0.029521,0.018549,1.405098e-03,1.388627e-02,0.436252,0.013417,0.000000e+00,1
22,0.132600,0.021319,7.343458e-25,1.406496e-02,0.438920,0.026352,0.000000e+00,1
23,0.429475,0.043023,9.491953e-118,1.077385e-02,0.486531,0.386901,0.000000e+00,1
24,0.000739,0.022413,4.324478e-17,1.217275e-01,0.143023,0.000268,1.429815e-41,3
25,0.003118,0.019486,1.148181e-28,1.438432e-01,0.385057,0.001343,2.275851e-73,1
26,0.001651,0.010811,1.779561e-07,1.587795e-01,0.430764,0.001082,3.129917e-104,1
27,0.002903,0.024707,3.160086e-02,1.462340e-01,0.431249,0.001311,2.190167e-90,1
28,0.000914,0.028416,2.383008e-01,5.287775e-02,0.430823,0.000124,0.000000e+00,1
29,0.000916,0.018898,1.407342e-01,4.301236e-02,0.431548,0.000150,0.000000e+00,1
...,...,...,...,...,...,...,...,...
34,0.003245,0.013123,2.533285e-04,2.026486e-01,0.431366,0.001649,1.024940e-34,3
35,0.002828,0.018632,2.504275e-01,1.239158e-01,0.432933,0.000241,7.764078e-81,1
36,0.000698,0.021919,4.444383e-01,5.141708e-02,0.408148,0.000176,0.000000e+00,4
37,0.002887,0.026399,9.688877e-02,5.875892e-02,0.531651,0.001044,0.000000e+00,1
38,0.002226,0.027959,2.611255e-29,4.136034e-02,0.571429,0.000486,0.000000e+00,1
39,0.005538,0.066561,3.139352e-110,1.190003e-02,0.571429,0.002086,0.000000e+00,1
40,0.000429,0.006231,2.633346e-05,3.823902e-01,0.121285,0.000466,5.001803e-10,3
41,0.000745,0.023730,3.870247e-04,4.027195e-01,0.310056,0.000537,1.354547e-22,3
42,0.000737,0.015311,5.633958e-07,3.419263e-01,0.437241,0.000355,2.440947e-23,3
43,0.000539,0.046903,1.447769e-01,1.687846e-01,0.429878,0.000129,1.527123e-13,1
44,0.003452,0.024032,7.430361e-01,7.954609e-02,0.443397,0.000164,9.006093e-16,4
45,0.001170,0.029516,2.984385e-01,2.538928e-02,0.597397,0.000095,1.663159e-16,4
46,0.000462,0.021780,4.800833e-06,1.123077e-01,0.571429,0.000153,2.220235e-44,1
47,0.001730,0.014207,3.145052e-73,1.388637e-02,0.571429,0.000973,0.000000e+00,1
48,0.000391,0.043307,4.845357e-03,6.352157e-01,0.210310,0.000129,1.527510e-17,3
49,0.007585,0.012040,1.694808e-05,4.919215e-01,0.428528,0.001999,8.822111e-06,3
50,0.002839,0.049906,5.540390e-03,3.181790e-01,0.431231,0.000973,1.762149e-01,3
51,0.005570,0.024243,3.844049e-01,8.069780e-02,0.428177,0.000780,3.315931e-01,4
52,0.010411,0.027108,2.657740e-01,4.689631e-02,0.466383,0.002256,1.913577e-01,4
53,0.007673,0.023596,2.442371e-02,5.407022e-02,0.526371,0.002055,1.609425e-01,1
54,0.001576,0.022382,1.885391e-50,5.238808e-02,0.633415,0.000517,6.538211e-03,1
55,0.000931,0.025691,0.000000e+00,3.733845e-02,0.656823,0.000406,0.000000e+00,1
56,0.001628,0.054714,2.306994e-01,8.714957e-01,0.140019,0.000319,4.515798e-10,5
57,0.000970,0.029165,1.768722e-01,5.574365e-01,0.421525,0.000389,9.806048e-04,3
58,0.002451,0.046619,7.114757e-03,4.741369e-01,0.422043,0.000764,2.844346e-01,3
59,0.004801,0.018709,1.211095e-14,1.038039e-01,0.397615,0.001599,8.006158e-01,6
60,0.010751,0.025733,5.122502e-11,4.182676e-02,0.444027,0.003137,4.712940e-01,6
61,0.012685,0.029542,3.580439e-21,2.914814e-02,0.456487,0.004124,3.333333e-01,6
62,0.005279,0.035143,9.876672e-40,2.085966e-02,0.647207,0.002104,2.385033e-01,1
63,0.001235,0.039845,5.200152e-58,4.513163e-02,0.747936,0.000374,1.134338e-06,1

In [130]:
df1 = df.loc[df['Cluster'] == 1]
df2 = df.loc[df['Cluster'] == 2]
df3 = df.loc[df['Cluster'] == 3]
df4 = df.loc[df['Cluster'] == 4]
df4 = df.loc[df['Cluster'] == 5]
df4 = df.loc[df['Cluster'] == 6]


df1.drop([df.columns[-1]], axis=1)
df2.drop([df.columns[-1]], axis=1)
df3.drop([df.columns[-1]], axis=1)
df4.drop([df.columns[-1]], axis=1)
df5.drop([df.columns[-1]], axis=1)
df6.drop([df.columns[-1]], axis=1)


df1.columns

Index(['Reviews', 'Size', 'Price', 'Last.Updated', 'Minimum.Android.Version',
       'install', 'Content', 'Cluster'],
      dtype='object')

In [128]:
lis = {}
for i in df1.columns:
    temp = []
    temp.append(sum(df1[i])/len(df1))
    temp.append(sum(df2[i])/len(df2))
    temp.append(sum(df3[i])/len(df3))
    temp.append(sum(df4[i])/len(df4))
    lis[i] = temp
lis

{'Reviews': [0.0019529212172701945,
  0.006717723763734989,
  0.032828965238778346,
  0.0023888891352554153],
 'Size': [0.028300031123398725,
  0.0202527616371812,
  0.05165595843435457,
  0.0242137443391365],
 'Price': [0.08844354738109163,
  3.12553168161106e-15,
  0.02214140965227496,
  0.5194074917756974],
 'Last.Updated': [0.5934668523024126,
  0.0910089755643729,
  0.07502022941272783,
  0.06743411393381854],
 'Minimum.Android.Version': [0.23632472757261533,
  0.4064573201530779,
  0.4398492119879795,
  0.4353722148811925],
 'install': [0.0005765311282943633,
  0.00210873061534175,
  0.02468338295224689,
  0.000158040471238857],
 'Content': [0.006389699898644834,
  0.7968486783572191,
  0.059428013796735346,
  1.34544283959745e-17],
 'Cluster': [1.0, 2.0, 3.0, 4.0]}

In [131]:
cluster_reps = pd.DataFrame(lis)

In [132]:
cluster_reps

,Reviews,Size,Price,Last.Updated,Minimum.Android.Version,install,Content,Cluster
0,0.001953,0.028300,8.844355e-02,0.593467,0.236325,0.000577,6.389700e-03,1.0
1,0.006718,0.020253,3.125532e-15,0.091009,0.406457,0.002109,7.968487e-01,2.0
2,0.032829,0.051656,2.214141e-02,0.075020,0.439849,0.024683,5.942801e-02,3.0
3,0.002389,0.024214,5.194075e-01,0.067434,0.435372,0.000158,1.345443e-17,4.0